public enum ChallengeCategory
{
    WinGame=0,
    CraftItem=1,
    CraftShard=2,
    GainExperience=3,
    GainLeaderboardPoints=4,
    WinWithFullHp=5,
    LoseMatch=6,
    DealDamage=7,
    UseMilkBottle=8,
    HealYourKitty=9,
    PlayMatch=10,
    ShootRocket=11,
    ShootCannon=12,
    ShootTripleRocket=13,
    ShootPlane=14,
    ShootMouse=15,
    ShootArrow=16,
    WinMatchesInARow=17,
    WinMatchWithLessThan10Hp=18,
    WinMatchWithLessThan20Hp=19,
    WinMatchWithLessThan30Hp=20
}
